### ISSUE TITLE
Path to procfs is not configurable

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-smart#14]
The path to procfs is currently hardcoded to /proc. This makes it hard (if even possible) to use the plugin when snapd is run in a Docker container.

**Comment by marcintao** [comment]
Could you explain what results do you expect from smart collector plugin and what results do you actually get?

Perhaps you could submit a PR adding a deployment script and/ or Dockerfile aiding in running the dockerized smart plugin? It would be great to see what steps you took to run the plugin in docker. That would definitely make many people happy.

**Comment by obourdon** [comment]
Fixed completely by PR #18 

@marcintao I am not sure I fully understand your previous question. However concerning the usage of this plugin within a Docker container, I have added the command I am using to launch the container into the [PR comments](https://github.com/intelsdi-x/snap-plugin-collector-smart/pull/18#issue-168097027)
I might consider adding a Dockerfile like suggested whenever time permits
HTH

**Comment by obourdon** [comment]
cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)

As the corresponding PR #18 is merged I think this should be closed

**Comment by IzabellaRaulin** [comment]
Resolved by #18
