### ISSUE TITLE
Gathered SMART metrics can be nil

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-smart#23]
Due to the [code here](https://github.com/intelsdi-x/snap-plugin-collector-smart/blob/master/smart/plugin.go#L174) unrelevant nil valued metrics are sent downstream the workflow
and I think this is not necessary.

The list of returned metrics should be built incerementally with only non nil valued metrics returned

**Comment by obourdon** [comment]
Proposed fix can be found for review in my [private branch](https://github.com/intelsdi-x/snap-plugin-collector-smart/commit/6b3f627937ca77efe36daa80df8ac35abf4a92db)

cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)

**Comment by mkuculyma** [comment]
Resolved by #24
